version: '3.8'

services:
  backend:
    image: ghcr.io/romanyurkin2024/film-backend:latest
    platform: linux/amd64
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DRIVER=postgres
      - LOGGER_TYPE=tskv
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - NODE_ENV=production
      - DATABASE_NAME=films
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ghcr.io/romanyurkin2024/film-frontend:latest
    platform: linux/amd64
    volumes:
      - frontend_static:/var/www/html
    restart: unless-stopped

  nginx:
    image: ghcr.io/romanyurkin2024/film-nginx:latest
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: film-postgres-image
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=films
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: film-pgadmin-image
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  frontend_static:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data: 
    driver: local