server {
    listen 80;
    server_name deploylab.nomorepartiessbs.ru 5.35.108.19;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
  listen 443 ssl;
  server_name deploylab.nomorepartiessbs.ru 5.35.108.19 localhost;

  ssl_certificate /etc/letsencrypt/live/deploylab.nomorepartiessbs.ru/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/deploylab.nomorepartiessbs.ru/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://backend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /content/ {
    proxy_pass http://backend:3000;
    proxy_set_header Host $host;
  }
}